apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-hook
  labels:
    app.kubernetes.io/name: nats-hook
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nats-hook
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nats-hook
    spec:
      containers:
        - name: nats-hook
          image: olpie101/nats-hook
          args:
            - "--addr"
            - "nats://nats.nats.svc.cluster.local:4222"
            - "--subject"
            - "public.webhooks.minio.assets.bridge-labs"
          volumeMounts:
            - name: nats-creds
              mountPath: /nats
          resources:
            requests:
              memory: 32Mi
            limits:
              cpu: 10m
              memory: 64Mi
      volumes:
        - name: nats-creds

