apiVersion: v1
kind: Service
metadata:
  name: nats-hook
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: nats-hook